FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json ./
COPY frontend/package.json ./frontend/
RUN npm install --workspace=frontend
COPY frontend ./frontend
WORKDIR /app/frontend
ENV VITE_API_URL=/api/v1
RUN npm run build

FROM nginx:alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
